### ISSUE TITLE
Random "Variable cannot be initialized with value" During Startup

### ISSUE THREAD

**Issue by dynostatic** [eclipse/smarthome#1650]
I'm experiencing random variable initialization errors in some of my rule files during startup. Sometimes the variables are initialized without issue, but then fail on a restart with no rule or config changes made in between. The problem seems limited to complex values using HashMap / LinkedHashMap.

```
10:50:31.080 [WARN ] [me.internal.engine.RuleContextHelper] - Variable 'tod_dimmer_values' on rule file '20_lights.rules' cannot be initialized with value 'newLinkedHashMap(<XBinaryOperationImplCustom>,<XBinaryOperationImplCustom>,<XBinaryOperationImplCustom>,<XBinaryOperationImplCustom>,<XBinaryOperationImplCustom>,<XBinaryOperationImplCustom>)': An error occured during the script execution: The name '<XStringLiteralImpl> -> <XNumberLiteralImpl>' cannot be resolved to an item or type.
```
I loaded the rules in the latest designer snapshot, and it didn't indicate any syntax errors. Here is the relevant variable declaration:

```
import org.eclipse.xtext.xbase.lib.*
import org.joda.time.DateTime
import java.text.DecimalFormat
import java.util.HashMap
import java.util.LinkedHashMap
import java.util.ArrayList
import java.util.Map
import java.util.Set

val HashMap<String, LinkedHashMap<String, Integer>> tod_dimmer_values =
	newLinkedHashMap(
		"Morning" -> (
			newLinkedHashMap(
				"DM_LT_Kitchen_1"		-> 25,
				"DM_LT_Kitchen_2"		-> 25,
				"DM_LT_LivingRoom_1"	-> 25,
				"DM_LT_LivingRoom_2"	-> 25
			)
		),
		"Day" -> (
			newLinkedHashMap(
				"DM_LT_Kitchen_1"		-> 0,
				"DM_LT_Kitchen_2"		-> 0,
				"DM_LT_LivingRoom_1"	-> 0,
				"DM_LT_LivingRoom_2"	-> 0
			)
		),
		"Day_Weather" -> (
			newLinkedHashMap(
				"DM_LT_Kitchen_1"		-> 25,
				"DM_LT_Kitchen_2"		-> 25,
				"DM_LT_LivingRoom_1"	-> 25,
				"DM_LT_LivingRoom_2"	-> 25
			)
		),
		"Twilight" -> (
			newLinkedHashMap(
				"DM_LT_Kitchen_1"		-> 25,
				"DM_LT_Kitchen_2"		-> 25,
				"DM_LT_LivingRoom_1"	-> 25,
				"DM_LT_LivingRoom_2"	-> 25
			)
		),
		"Evening" -> (
			newLinkedHashMap(
				"DM_LT_Kitchen_1"		-> 35,
				"DM_LT_Kitchen_2"		-> 35,
				"DM_LT_LivingRoom_1"	-> 35,
				"DM_LT_LivingRoom_2"	-> 35
			)
		),
		"Night" -> (
			newLinkedHashMap(
				"DM_LT_Kitchen_1"		-> 0,
				"DM_LT_Kitchen_2"		-> 0,
				"DM_LT_LivingRoom_1"	-> 35,
				"DM_LT_LivingRoom_2"	-> 35
			)
		)
	)
```

**Comment by dynostatic** [comment]
I've been searching around in other discussions for something related, and I'm pretty sure these errors are directly related to the xtext upgrade discussed in #1393. The same vars never had a problem until then.

**Comment by dynostatic** [comment]
I tried explicitly casting all of the map members (which the designer correctly flagged as redundant).

```
val HashMap<String, LinkedHashMap<String, Integer>> tod_dimmer_values =
	newHashMap(
		"Morning" -> (
			newLinkedHashMap(
				"DM_LT_Kitchen_1"		-> 25,
				"DM_LT_Kitchen_2"		-> 25,
				"DM_LT_LivingRoom_1"	-> 25,
				"DM_LT_LivingRoom_2"	-> 25
			)
			as LinkedHashMap<String, Integer>
		),
		"Day" -> (
			newLinkedHashMap(
				"DM_LT_Kitchen_1"		-> 0,
				"DM_LT_Kitchen_2"		-> 0,
				"DM_LT_LivingRoom_1"	-> 0,
				"DM_LT_LivingRoom_2"	-> 0
			)
			as LinkedHashMap<String, Integer>
		)
	)
	as HashMap<String, LinkedHashMap<String, Integer>>
```
Now same problem, just a slightly different error. Eight restarts were fine, and then it failed.

```
11:48:44.639 [WARN ] [me.internal.engine.RuleContextHelper] - Variable 'tod_dimmer_values' on rule file '20_lights.rules' cannot be initialized with value 'org.eclipse.xtext.xbase.impl.XCastedExpressionImpl@1ea6031': An error occured during the script execution: The name '<XStringLiteralImpl> -> <XCastedExpressionImpl>' cannot be resolved to an item or type.
```

**Comment by kaikreuzer** [comment]
Some good and some bad news:
I managed to reproduce it on my RPi3, but I fail to see the effect on my MacBook. So I assume it is related to the slower startup behavior. Unfortunately, I noticed that remote debugging a RPi does not really work - it is so slow that simply nothing happens.

This effectively means that I don't really have a clue on how to best analyze the startup behavior...
If someone finds a way to stop/start bundles in a certain way that makes this problem appear, it would be superb for the analysis...

**Comment by dynostatic** [comment]
My test machine is a NUC with an i5, so I don't think it's limited to a slower startup. Perhaps my specific collection of rules is more susceptible to triggering the underlying timing issue? Merging all of my items into one file helped solve some weird startup errors on the earlier betas. My rules are still split into about ten files. I'm not sure if that makes any difference for this issue.

I haven't played around with remote debugging, but I should be able to get it up and running. I'll see if I can find anything useful since I don't have a problem reproducing it.

**Comment by alfista2600** [comment]
I've just read through the notes on this issue, as it just started appearing for me on a RPI3. I'm no expert, but wanted to report a finding. I was getting this error on two rules. If I delete the rules without stopping/restarting the service, I continue to get the errors - even without the rules in the file.

**Comment by kaikreuzer** [comment]
Can you tell me which bundle version you are currently using?
I wonder if the problem still exists now that https://github.com/eclipse/smarthome/issues/870 is happening again.

I have a setup with 30-40 rules in 10 different files and am using the lastest OH2 build (ESH bundles 0.9.0.201606220943). I restarted the runtime many times, but didn't have any issue a single time. It is really weird that I cannot reproduce it...
@kgoderis Also still asking you for help on how to reproduce your problems best - I definitely would like to help to sort this out, but without being able to reproduce it, I am having a hard time.

**Comment by kgoderis** [comment]
@kaikreuzer If you are making a reference to the recent Xtext discussion we had, I must say that making the .rules syntax-perfect resolved my issues, including removing depreciated declarations and alike. I personally do not use Hashmaps in my rules. That being said, at the time I also experienced some randomness in the errors I faced.

**Comment by kaikreuzer** [comment]
@kgoderis Yes, this is what I was referring to (mainly the "ScriptInterpreter not found" messages and alike). I am very glad to hear that this seem to be solved now for you. So I assume you withdraw your request to downgrade Xtext again? :-)
In any case, whenever you can specify your remaining random errors, please do report them.

**Comment by dynostatic** [comment]
I'm running bundle 0.9.0.201606271819 as of today, and the issue persists. It sounds like we have about the same size setup. I haven't had a chance to do any debugging yet, but I hope to have some time tomorrow.

**Comment by dynostatic** [comment]
@kaikreuzer What information will be useful to you from a remote debug? I'm a bit new to some of this. I can connect and view the thread stack in the debugger, but I'm not sure where to go from here. I captured the stack from a good and bad startup, but I don't know if that helps or not.

**Comment by triller-telekom** [comment]
After more than one year of no activity and yet another [Xtext update](https://github.com/eclipse/smarthome/pull/4149), either the problem has been fixed or @dynostatic please feel free to re-open the issue.

@kaikreuzer @sjka Can you please close this issue?

**Comment by kaikreuzer** [comment]
Isn't that the same as https://github.com/eclipse/smarthome/issues/3577? If so, it means that it still exists, but that we might want to merge the reports into a single issue and mark the other as a duplicate.

**Comment by lolodomo** [comment]
Mine is still present and systematic at each OH startup. It is the most critical issue I have with OH.

**Comment by triller-telekom** [comment]
Looks like this is indeed a duplicate. @kaikreuzer Can you please add a duplicate label on this issue and close it in favor to #3577?

**Comment by kaikreuzer** [comment]
I'd actually prefer it the other way round, because this issue here was first.

But to not loose @lolodomo's example, I repeat it here:

----
In my rule file, I have at top few global variables:
```
import org.joda.time.*
import java.util.regex.Matcher
import java.util.regex.Pattern

var DateTime lastDesarmTime = now.minusDays(1)
var boolean initMinimoteCourt = true
var boolean initMinimoteLong = true
val Pattern patternVoice1 = Pattern::compile("(donner|passer en hors gel|passer en mode confort|passer en mode réduit) (le |la |les |l'|du )(.*) (du |de la |de l'|dans le |dans la |dans l')(.*)")
val Pattern pattern2 = Pattern::compile("x-sonosapi-stream:s(\\d+?)\\?.+")
val Pattern pattern3 = Pattern::compile("x-rincon:.+")
var String voice = "voicerss:frFR"
```
With new installed build 937, at startup, I have now these warnings:
```
2017-06-03 12:46:26.828 [WARN ] [me.internal.engine.RuleContextHelper] - Variable 'lastDesarmTime' on rule file 'maison.rules' cannot be initialized with value '<XFeatureCallImplCustom>.minusDays(<XNumberLiteralImpl>)': An error occurred during the script execution: The name '<XFeatureCallImplCustom>.minusDays(<XNumberLiteralImpl>)' cannot be resolved to an item or type.
2017-06-03 12:46:26.864 [WARN ] [me.internal.engine.RuleContextHelper] - Variable 'patternVoice1' on rule file 'maison.rules' cannot be initialized with value '<XFeatureCallImplCustom>::compile(<XStringLiteralImpl>)': An error occurred during the script execution: The name 'Pattern' cannot be resolved to an item or type.
2017-06-03 12:46:26.873 [WARN ] [me.internal.engine.RuleContextHelper] - Variable 'pattern2' on rule file 'maison.rules' cannot be initialized with value '<XFeatureCallImplCustom>::compile(<XStringLiteralImpl>)': An error occurred during the script execution: The name 'Pattern' cannot be resolved to an item or type.
2017-06-03 12:46:26.881 [WARN ] [me.internal.engine.RuleContextHelper] - Variable 'pattern3' on rule file 'maison.rules' cannot be initialized with value '<XFeatureCallImplCustom>::compile(<XStringLiteralImpl>)': An error occurred during the script execution: The name 'Pattern' cannot be resolved to an item or type.
```
It looks like all variable init that use a call to a function are failing.
Then my rules are failing because the variable pattern2 is null (for example).

What was changed ? Is there a new way to define global variables ?

PS: With the previous installed builds, it was always working as expected (my previous installed snapshot was 889).
```

**Comment by dynostatic** [comment]
I can confirm that I still see this occasionally. It did drastically improve as newer builds came out, so I mostly forgot about it.
