### ISSUE TITLE
WeMo Binding will not pull device status or fire event updates on restart

### ISSUE THREAD

**Issue by DigitalBites** [eclipse/smarthome#2446]

**Comment by DigitalBites** [comment]
Lots more details at the link below - this is to fix the issue of having to restart the binding after openHab2 restarts. Will provide a pull request after I've completed my testing.

https://community.openhab.org/t/wemo-insight-switch-not-initalized-after-start-openhab2/15921/10?u=digitalbites

**Comment by DigitalBites** [comment]
#2447 should fix this. :)

**Comment by triller-telekom** [comment]
@DigitalBites: Did your PR fix the problem or can you still reproduce it?

**Comment by hmerk** [comment]
@triller-telekom #2617 which was merged Dezember 7th 2016.
This issue can be closed.
