### ISSUE TITLE
RuleEngine PaperUI 503 Service Unavailable if marketplace bundles NOT installed

### ISSUE THREAD

**Issue by triller-telekom** [eclipse/smarthome#3788]
If you start ESH with only the `*automation*` bundles activated that are unrelated to the Eclipse Marketplace, then clicking on the `Rule` menu entry in PaperUI results in the following request:

```
Request URL:http://localhost:8080/rest/extensions
Request Method:GET
Status Code:503 Service Unavailable
```

Somehow the PaperUI tries to query the endpoint `extensions`, but this is only installed if the marketplace extensions are also activated.

**Comment by maggu2810** [comment]
Isn't this similar to #3591 that has been solved by #3627?
Is this problem present again?

**Comment by triller-telekom** [comment]
I just tried it again and it still shows me the 503 error if the marketplace extensions are not installed, once I click on "Rules". But it looks like the very same problem like in the issue you link to.

**Comment by triller-telekom** [comment]
Sorry my bad... I forgot a "mvn install" in `extensions/ui/org.eclipse.smarthome.ui.paper`. So my Eclipse was using an old paper ui version
