### ISSUE TITLE
Thread:sleep pauses whole rule engine.

### ISSUE THREAD

**Issue by hannibal85** [eclipse/smarthome#4103]
Hi all,

I hope this is the right repo for this issue.

Following situation:
I have a rule where I use Thread::sleep for 60sec. During this 60sec all rules are paused, even if they are distributed across multiple files.

After encountering this behaviour in a quite complex setup I could proof it with a minimal setup just for this purpose (see below). Test with OH2.1.0 stable and OH2.2.0 snapshot build 1070 with same result. Both as a local installation on Ubuntu 16.04

Would be great if someone can proof this is a bug or not. Maybe I'm missing something.
See also [this thread in the OH forum](https://community.openhab.org/t/question-about-thread-sleep/33290)

Here is my minimal example:

Items:
```
Switch StartUp      "StartUp Switch"   // triggers rules to with defined delay after system startup
Switch TestSwitch   "Test Switch"      // to test manuell rule triggers during delay
String Result       "Result"           // shows result string 
```

Rule file 1:
```
rule "StartUp"
when
  System started
then
  logDebug("RULES", "+++ Rule 'StartUp' started +++")
  StartUp.sendCommand(OFF)
  Thread::sleep(60000)
  StartUp.sendCommand(ON)
  Thread::sleep(3000)
  StartUp.sendCommand(OFF)
  logDebug("RULES", "--- Rule 'StartUp' completed ---")
end
```

Rule file 2:
```
rule "Test"
when
  Item TestSwitch received command
then
  logDebug("RULES", "+++ Rule 'Test' started +++")
  Result.postUpdate("Test rule triggered via REST")
  logDebug("RULES", "--- Rule 'Test' completed ---")
end

rule "Test2"
when
  Item StartUp received command ON
then
  logDebug("RULES", "+++ Rule 'Test2' started +++")
  Result.postUpdate("Test2 rule triggered via StartUp rule")
  logDebug("RULES", "--- Rule 'Test2' completed ---")
end
```

And here is the log (with some manually added comments) for the trail with OH 2.1.0
```
*** STARTUP openhab 2.1.0 release build ***

2017-08-18 18:40:15.749 [INFO ] [org.apache.felix.fileinstall        ] - Updating configuration from org.ops4j.pax.logging.cfg
2017-08-18 18:40:16.283 [WARN ] [les.properties.AutoEncryptionSupport] - User limit of inotify watches reached
java.io.IOException: User limit of inotify watches reached
	at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264)[:1.8.0_144]
	at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)[:1.8.0_144]
	at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329)[:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_144]
2017-08-18 18:40:16.345 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.bundle.core/4.0.8
2017-08-18 18:40:16.364 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.config.core/4.0.8
2017-08-18 18:40:16.370 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.deployer.kar/4.0.8
2017-08-18 18:40:16.372 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.diagnostic.core/4.0.8
2017-08-18 18:40:16.404 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.features.command/4.0.8
2017-08-18 18:40:16.408 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.http.core/4.0.8
2017-08-18 18:40:16.438 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.instance.core/4.0.8
2017-08-18 18:40:16.530 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.jaas.command/4.0.8
2017-08-18 18:40:16.532 [INFO ] [ll.impl.action.osgi.CommandExtension] - Updating commands for bundle org.apache.karaf.jaas.command/4.0.8
2017-08-18 18:40:16.538 [INFO ] [ll.impl.action.osgi.CommandExtension] - Updating commands for bundle org.apache.karaf.jaas.command/4.0.8
2017-08-18 18:40:16.546 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.kar.core/4.0.8
2017-08-18 18:40:16.565 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.log.core/4.0.8
2017-08-18 18:40:16.568 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.package.core/4.0.8
2017-08-18 18:40:16.579 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.scr.command/4.0.8
2017-08-18 18:40:16.583 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.service.core/4.0.8
2017-08-18 18:40:16.618 [INFO ] [ll.impl.action.osgi.CommandExtension] - Command registration delayed for bundle org.apache.karaf.shell.commands/4.0.8. Missing dependencies: [org.jledit.EditorFactory]
2017-08-18 18:40:16.807 [INFO ] [ll.impl.action.osgi.CommandExtension] - Command registration delayed for bundle org.apache.karaf.shell.ssh/4.0.8. Missing dependencies: [org.apache.sshd.SshServer]
2017-08-18 18:40:16.812 [INFO ] [pache.sshd.common.util.SecurityUtils] - BouncyCastle not registered, using the default JCE provider
2017-08-18 18:40:16.820 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.system.core/4.0.8
2017-08-18 18:40:16.877 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.shell.commands/4.0.8
2017-08-18 18:40:16.895 [INFO ] [j.pax.web.service.internal.Activator] - EventAdmin support enabled, servlet events will be postet to topics.
2017-08-18 18:40:16.897 [INFO ] [j.pax.web.service.internal.Activator] - LogService support enabled, log events will be created.
2017-08-18 18:40:16.899 [INFO ] [j.pax.web.service.internal.Activator] - Pax Web started
2017-08-18 18:40:16.992 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.shell.ssh/4.0.8
2017-08-18 18:40:17.032 [INFO ] [org.eclipse.jetty.util.log          ] - Logging initialized @2298ms
2017-08-18 18:40:17.216 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.apache.karaf.wrapper.core/4.0.8
2017-08-18 18:40:17.271 [INFO ] [rvice.jetty.internal.JettyServerImpl] - Pax Web available at [0.0.0.0]:[8443]
2017-08-18 18:40:17.272 [INFO ] [vice.jetty.internal.JettyFactoryImpl] - SPDY not available, creating standard ServerConnector for Http
2017-08-18 18:40:17.273 [INFO ] [rvice.jetty.internal.JettyServerImpl] - Pax Web available at [0.0.0.0]:[8080]
2017-08-18 18:40:17.280 [INFO ] [vice.internal.HttpServiceFactoryImpl] - Binding bundle: [com.eclipsesource.jaxrs.publisher_5.3.1.201602281253 [9]] to http service
2017-08-18 18:40:17.342 [INFO ] [vice.internal.HttpServiceFactoryImpl] - Binding bundle: [org.openhab.io.rest.docs_2.1.0 [194]] to http service
2017-08-18 18:40:17.384 [INFO ] [rg.ops4j.pax.web.utils.ClassPathUtil] - Ignoring bundle scan for /META-INF/services javax.servlet.ServletContainerInitializer.
2017-08-18 18:40:17.423 [INFO ] [ce.jetty.internal.HttpServiceContext] - registering context DefaultHttpContext [bundle=org.openhab.io.rest.docs_2.1.0 [194], contextID=default], with context-name: 
2017-08-18 18:40:17.483 [INFO ] [.jetty.server.handler.ContextHandler] - Started HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.openhab.io.rest.docs_2.1.0 [194], contextID=default]}
2017-08-18 18:40:17.502 [INFO ] [org.eclipse.jetty.server.Server     ] - jetty-9.2.19.v20160908
2017-08-18 18:40:17.545 [INFO ] [.jetty.server.handler.ContextHandler] - Started o.e.j.s.h.ContextHandler@66800add{/static,null,AVAILABLE}
2017-08-18 18:40:17.599 [INFO ] [eclipse.jetty.server.ServerConnector] - Started 0.0.0.0:8443@10bc9073{SSL-http/1.1}{0.0.0.0:8443}
2017-08-18 18:40:17.603 [INFO ] [eclipse.jetty.server.ServerConnector] - Started default@743d90eb{HTTP/1.1}{0.0.0.0:8080}
2017-08-18 18:40:17.603 [INFO ] [org.eclipse.jetty.server.Server     ] - Started @2869ms
2017-08-18 18:40:17.633 [INFO ] [vice.internal.HttpServiceFactoryImpl] - Binding bundle: [org.openhab.ui.dashboard_2.1.0 [170]] to http service
2017-08-18 18:40:17.640 [INFO ] [rg.ops4j.pax.web.utils.ClassPathUtil] - Ignoring bundle scan for /META-INF/services javax.servlet.ServletContainerInitializer.
2017-08-18 18:40:17.646 [INFO ] [ce.jetty.internal.HttpServiceContext] - registering context DefaultHttpContext [bundle=org.openhab.ui.dashboard_2.1.0 [170], contextID=default], with context-name: 
2017-08-18 18:40:17.659 [INFO ] [.jetty.server.handler.ContextHandler] - Started HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.openhab.ui.dashboard_2.1.0 [170], contextID=default]}
2017-08-18 18:40:17.663 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://192.168.178.20:8080
2017-08-18 18:40:17.664 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://192.168.178.20:8443
2017-08-18 18:40:17.983 [INFO ] [vice.internal.HttpServiceFactoryImpl] - Binding bundle: [org.eclipse.smarthome.core.audio_0.9.0.b5 [99]] to http service
2017-08-18 18:40:18.003 [INFO ] [rg.ops4j.pax.web.utils.ClassPathUtil] - Ignoring bundle scan for /META-INF/services javax.servlet.ServletContainerInitializer.
2017-08-18 18:40:18.008 [INFO ] [ce.jetty.internal.HttpServiceContext] - registering context DefaultHttpContext [bundle=org.eclipse.smarthome.core.audio_0.9.0.b5 [99], contextID=default], with context-name: 
2017-08-18 18:40:18.011 [INFO ] [.jetty.server.handler.ContextHandler] - Started HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.eclipse.smarthome.core.audio_0.9.0.b5 [99], contextID=default]}
2017-08-18 18:40:18.100 [INFO ] [rg.ops4j.pax.web.utils.ClassPathUtil] - Ignoring bundle scan for /META-INF/services javax.servlet.ServletContainerInitializer.
2017-08-18 18:40:18.104 [INFO ] [ce.jetty.internal.HttpServiceContext] - registering context DefaultHttpContext [bundle=com.eclipsesource.jaxrs.publisher_5.3.1.201602281253 [9], contextID=default], with context-name: 
2017-08-18 18:40:18.108 [INFO ] [.jetty.server.handler.ContextHandler] - Started HttpServiceContext{httpContext=DefaultHttpContext [bundle=com.eclipsesource.jaxrs.publisher_5.3.1.201602281253 [9], contextID=default]}
2017-08-18 18:40:18.165 [INFO ] [org.quartz.impl.StdSchedulerFactory ] - Using default implementation for ThreadExecutor
2017-08-18 18:40:18.196 [INFO ] [rg.quartz.core.SchedulerSignalerImpl] - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2017-08-18 18:40:18.196 [INFO ] [org.quartz.core.QuartzScheduler     ] - Quartz Scheduler v.2.2.1 created.
2017-08-18 18:40:18.197 [INFO ] [org.quartz.simpl.RAMJobStore        ] - RAMJobStore initialized.
2017-08-18 18:40:18.198 [INFO ] [org.quartz.core.QuartzScheduler     ] - Scheduler meta-data: Quartz Scheduler (v2.2.1) 'openHAB-job-scheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 2 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2017-08-18 18:40:18.199 [INFO ] [org.quartz.impl.StdSchedulerFactory ] - Quartz scheduler 'openHAB-job-scheduler' initialized from specified file: '/opt/openhab/openhab2_Testsystem_2-1/runtime/etc/quartz.properties'
2017-08-18 18:40:18.199 [INFO ] [org.quartz.impl.StdSchedulerFactory ] - Quartz scheduler version: 2.2.1
2017-08-18 18:40:18.199 [INFO ] [org.quartz.core.QuartzScheduler     ] - Scheduler openHAB-job-scheduler_$_NON_CLUSTERED started.
2017-08-18 18:40:20.211 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'main.items'
2017-08-18 18:40:20.242 [INFO ] [smarthome.event.ItemAddedEvent      ] - Item 'StartUp' has been added.
2017-08-18 18:40:20.263 [INFO ] [smarthome.event.ItemAddedEvent      ] - Item 'TestSwitch' has been added.
2017-08-18 18:40:20.265 [INFO ] [smarthome.event.ItemAddedEvent      ] - Item 'Result' has been added.
2017-08-18 18:40:20.464 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'mapdb.persist'
2017-08-18 18:40:21.841 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'two.rules'
2017-08-18 18:40:22.049 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'one.rules'
2017-08-18 18:40:22.227 [INFO ] [org.quartz.core.QuartzScheduler     ] - JobFactory set to: org.eclipse.smarthome.model.rule.runtime.internal.engine.GuiceAwareJobFactory@6d03497a
2017-08-18 18:40:22.228 [INFO ] [org.quartz.core.QuartzScheduler     ] - Scheduler openHAB-job-scheduler_$_NON_CLUSTERED paused.
2017-08-18 18:40:22.446 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'main.things'
2017-08-18 18:40:22.448 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model 'main.things' is either empty or cannot be parsed correctly!
2017-08-18 18:40:22.506 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'Strip_Brightness-milight:rgbLed:ACCF23DBA370:5:ledbrightness' has been added.
2017-08-18 18:40:22.507 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'LocalSun_Rise-astro:sun:local:rise#start' has been added.
2017-08-18 18:40:22.508 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'FernseherWZ_ButtonPress-harmonyhub:device:Wohnzimmer:36437306:buttonPress' has been added.
2017-08-18 18:40:22.520 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'HABServer192168178190_Online-network:device:192_168_178_190:online' has been added.
2017-08-18 18:40:22.521 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'LocalTime_Date-ntp:ntp:local:string' has been added.
2017-08-18 18:40:22.523 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'Bulb_Brightness-milight:whiteLed:ACCF23DBA370:1:ledbrightness' has been added.
2017-08-18 18:40:22.665 [INFO ] [vice.internal.HttpServiceFactoryImpl] - Binding bundle: [org.eclipse.smarthome.ui_0.9.0.b5 [136]] to http service
2017-08-18 18:40:22.749 [INFO ] [rg.ops4j.pax.web.utils.ClassPathUtil] - Ignoring bundle scan for /META-INF/services javax.servlet.ServletContainerInitializer.
2017-08-18 18:40:22.762 [INFO ] [ce.jetty.internal.HttpServiceContext] - registering context DefaultHttpContext [bundle=org.eclipse.smarthome.ui_0.9.0.b5 [136], contextID=default], with context-name: 
2017-08-18 18:40:22.810 [INFO ] [.jetty.server.handler.ContextHandler] - Started HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.eclipse.smarthome.ui_0.9.0.b5 [136], contextID=default]}
2017-08-18 18:40:22.845 [INFO ] [vice.internal.HttpServiceFactoryImpl] - Binding bundle: [org.eclipse.smarthome.ui.icon_0.9.0.b5 [137]] to http service
2017-08-18 18:40:22.852 [INFO ] [rg.ops4j.pax.web.utils.ClassPathUtil] - Ignoring bundle scan for /META-INF/services javax.servlet.ServletContainerInitializer.
2017-08-18 18:40:22.861 [INFO ] [ce.jetty.internal.HttpServiceContext] - registering context DefaultHttpContext [bundle=org.eclipse.smarthome.ui.icon_0.9.0.b5 [137], contextID=default], with context-name: 
2017-08-18 18:40:22.864 [INFO ] [.jetty.server.handler.ContextHandler] - Started HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.eclipse.smarthome.ui.icon_0.9.0.b5 [137], contextID=default]}
2017-08-18 18:40:22.931 [INFO ] [vice.internal.HttpServiceFactoryImpl] - Binding bundle: [org.jupnp_2.2.0 [162]] to http service
2017-08-18 18:40:22.962 [INFO ] [rg.ops4j.pax.web.utils.ClassPathUtil] - Ignoring bundle scan for /META-INF/services javax.servlet.ServletContainerInitializer.
2017-08-18 18:40:22.967 [INFO ] [ce.jetty.internal.HttpServiceContext] - registering context org.jupnp.transport.impl.osgi.DisableAuthenticationHttpContext@5adbbc8d, with context-name: 
2017-08-18 18:40:22.981 [INFO ] [.jetty.server.handler.ContextHandler] - Started HttpServiceContext{httpContext=org.jupnp.transport.impl.osgi.DisableAuthenticationHttpContext@5adbbc8d}
2017-08-18 18:40:23.083 [INFO ] [ll.impl.action.osgi.CommandExtension] - Registering commands for bundle org.openhab.core.karaf/2.1.0
2017-08-18 18:40:23.522 [INFO ] [vice.internal.HttpServiceFactoryImpl] - Binding bundle: [org.eclipse.smarthome.ui.basic_0.9.0.b5 [190]] to http service
2017-08-18 18:40:23.527 [INFO ] [rg.ops4j.pax.web.utils.ClassPathUtil] - Ignoring bundle scan for /META-INF/services javax.servlet.ServletContainerInitializer.
2017-08-18 18:40:23.532 [INFO ] [ce.jetty.internal.HttpServiceContext] - registering context DefaultHttpContext [bundle=org.eclipse.smarthome.ui.basic_0.9.0.b5 [190], contextID=default], with context-name: 
2017-08-18 18:40:23.547 [INFO ] [.jetty.server.handler.ContextHandler] - Started HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.eclipse.smarthome.ui.basic_0.9.0.b5 [190], contextID=default]}
2017-08-18 18:40:23.739 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2017-08-18 18:40:23.860 [INFO ] [vice.internal.HttpServiceFactoryImpl] - Binding bundle: [org.eclipse.smarthome.ui.classic_0.9.0.b5 [191]] to http service
2017-08-18 18:40:23.894 [INFO ] [rg.ops4j.pax.web.utils.ClassPathUtil] - Ignoring bundle scan for /META-INF/services javax.servlet.ServletContainerInitializer.
2017-08-18 18:40:23.908 [INFO ] [ce.jetty.internal.HttpServiceContext] - registering context DefaultHttpContext [bundle=org.eclipse.smarthome.ui.classic_0.9.0.b5 [191], contextID=default], with context-name: 
2017-08-18 18:40:23.915 [INFO ] [.jetty.server.handler.ContextHandler] - Started HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.eclipse.smarthome.ui.classic_0.9.0.b5 [191], contextID=default]}
2017-08-18 18:40:23.917 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2017-08-18 18:40:23.980 [INFO ] [vice.internal.HttpServiceFactoryImpl] - Binding bundle: [org.eclipse.smarthome.ui.paper_0.9.0.b5 [192]] to http service
2017-08-18 18:40:23.990 [INFO ] [rg.ops4j.pax.web.utils.ClassPathUtil] - Ignoring bundle scan for /META-INF/services javax.servlet.ServletContainerInitializer.
2017-08-18 18:40:23.993 [INFO ] [ce.jetty.internal.HttpServiceContext] - registering context DefaultHttpContext [bundle=org.eclipse.smarthome.ui.paper_0.9.0.b5 [192], contextID=default], with context-name: 
2017-08-18 18:40:23.998 [INFO ] [.jetty.server.handler.ContextHandler] - Started HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.eclipse.smarthome.ui.paper_0.9.0.b5 [192], contextID=default]}
2017-08-18 18:40:23.999 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
2017-08-18 18:40:24.306 [INFO ] [vice.internal.HttpServiceFactoryImpl] - Binding bundle: [org.openhab.core_2.1.0 [166]] to http service
2017-08-18 18:40:24.315 [INFO ] [rg.ops4j.pax.web.utils.ClassPathUtil] - Ignoring bundle scan for /META-INF/services javax.servlet.ServletContainerInitializer.
2017-08-18 18:40:24.320 [INFO ] [ce.jetty.internal.HttpServiceContext] - registering context DefaultHttpContext [bundle=org.openhab.core_2.1.0 [166], contextID=default], with context-name: 
2017-08-18 18:40:24.339 [INFO ] [.jetty.server.handler.ContextHandler] - Started HttpServiceContext{httpContext=DefaultHttpContext [bundle=org.openhab.core_2.1.0 [166], contextID=default]}

*** HERE WE GO ***

** Startup rule is triggered by 'System started' **

2017-08-18 18:40:27.740 [DEBUG] [eclipse.smarthome.model.script.RULES] - +++ Rule 'StartUp' started +++
2017-08-18 18:40:27.747 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'StartUp' received command OFF
2017-08-18 18:40:27.754 [INFO ] [marthome.event.ItemStateChangedEvent] - StartUp changed from NULL to OFF

** Manually trigger TestSwitch via REST while Thread::sleep is counting -> Rule 'Test' is NOT triggered**

2017-08-18 18:40:35.972 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'TestSwitch' received command ON
2017-08-18 18:40:35.973 [INFO ] [marthome.event.ItemStateChangedEvent] - TestSwitch changed from NULL to ON
2017-08-18 18:40:41.306 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'TestSwitch' received command ON
2017-08-18 18:40:46.807 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'TestSwitch' received command ON
2017-08-18 18:40:54.508 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'TestSwitch' received command ON
2017-08-18 18:41:12.447 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'TestSwitch' received command ON

** Thread::sleep is over -> change item 'StartUp' immediately followed by another Thread:sleep -> rule 'Test2' is NOT triggered ** 
 
2017-08-18 18:41:27.753 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'StartUp' received command ON
2017-08-18 18:41:27.763 [INFO ] [marthome.event.ItemStateChangedEvent] - StartUp changed from OFF to ON
2017-08-18 18:41:30.753 [DEBUG] [eclipse.smarthome.model.script.RULES] - --- Rule 'StartUp' completed ---

** What is this? **

2017-08-18 18:41:30.758 [INFO ] [org.quartz.core.QuartzScheduler     ] - Scheduler openHAB-job-scheduler_$_NON_CLUSTERED started.

** Rule 'Startup' finished **

2017-08-18 18:41:30.758 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'StartUp' received command OFF
2017-08-18 18:41:30.761 [INFO ] [marthome.event.ItemStateChangedEvent] - StartUp changed from ON to OFF

** Manually trigger TestSwitch via REST -> Rule 'Test' is triggered**

2017-08-18 18:41:31.132 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'TestSwitch' received command ON
2017-08-18 18:41:31.153 [DEBUG] [eclipse.smarthome.model.script.RULES] - +++ Rule 'Test' started +++
2017-08-18 18:41:31.155 [DEBUG] [eclipse.smarthome.model.script.RULES] - --- Rule 'Test' completed ---
2017-08-18 18:41:31.157 [INFO ] [marthome.event.ItemStateChangedEvent] - Result changed from NULL to Test rule triggered via REST
```

**Comment by kaikreuzer** [comment]
> I have a rule where I use Thread::sleep for 60sec.

Well, I would say it is a bug that such a thing is possible within the rules at all. In general, `Thread::sleep` should not be used and if, only for very pausing very short periods of time. The rule engine uses a thread pool and hence single rules must not block such threads.

The much better idea is to use the `createTimer` method with code blocks as a closure - this allows you to easily say that you want something else to happen a minute later or so without having to block any thread.

**Comment by kaikreuzer** [comment]
I'd suggest to close this as a won't fix as it is rather an unpattern to use it that way.

**Comment by hannibal85** [comment]
Ok.
I know that using Thread::sleep with such a long time is not recommended and a timer is the better solution. Was just for a testing situation.
But one more question: Does this mean using Thread::sleep should not be used at all? I think the usage with short times (300ms) is quite common. So I tried it again with a Thread::sleep(300) and the result is the same.

**Comment by rkoshak** [comment]
Even if someone used only Thread:sleep(300), isn't it still bad behavior for the whole rules engine to stop rather than just that one rule?

If someone has even just a few of these minimal sleeps scattered throughout their rules it could add up to real problems.

This used to work just fine.

To me, it seems to be better to either fix or eliminate the possibility of using Thread::sleep all-together. Leaving it as a problem that won't be fixed to me will lead to subtle problems for users in the long run.

I'm reminded of the old joke:

Patient: Doctor, it hurts when I move my arm like this!
Doctor: Then don't move it like that.

**Comment by LightIsLife** [comment]
Would like to add my support to @rkoshak; not only is this simply bad behavior of software, this will likely cause quite some trouble for all the users who try to figure out their problems or just starting to write rules by reading the forum. Thread::sleep is deeply ingrained in many, many blog-posts as a solution. It will take many a user many eons to figure out why their system is misbehaving.
Not that I understand what is involved in fixing this issue, but staying quiet on it, will likely alienate and frustrate the majority of users.

**Comment by kaikreuzer** [comment]
> isn't it still bad behavior for the whole rules engine to stop rather than just that one rule?

Yes indeed. Sorry, I have to admit that I didn't get that it blocks everything - I thought it is an exhausted thread pool which leads to no rules being executed because too many are sleeping.
So thanks for pointing it out and let's reopen the issue.

> This used to work just fine.

This actually surprises me - I am not aware of any change that could have changed anything in this behavior. Do you recall WHEN it was still working?

**Comment by rkoshak** [comment]
Unfortunately, I don't. And I may be remembering back to the good old 1.8.3 days when I ran these sorts of experiments, and even then I was never that rigorous so I could be mistaken that it actually was working. I was looking to learn about a different behavior at the time with Timers.

Since then I've always used tiny sleeps so I wouldn't have noticed. I probably shouldn't have claimed it used to work because now I question myself whether that is true.

But in the OP's example above only three Rules threads are being used which I believe/hope is less than the full thread pool. 

However, now that I'm looking at it more closely, it might be the case that the example the OP put together to show the behavior has more to do with a problem as system startup and the number of threads available in the thread pool. From looking at the logs I see:

System stated rule starts executing
System started rule sends OFF to Startup command which gets processed by the bus
System started rule Thread::sleeps for a minute
User manually commands TestSwitch to ON which gets processed by the bus
**"Test" rule does not trigger**
System started Thread::sleep ends
System started rule sends ON command to Startup which gets processed by the Bus
**"Test 2" rule does not trigger**
System started rule sends OFF command to Startup 
System started rule exits

The "Test" and "Test2" rules never trigger as a result of the System started or manual commands that were sent.

Once the System started rule exits, the Rules do trigger as expected.

So now I'm thinking this particular code might be showing a different problem (or expected behavior?) where commands sent while a System started rule is executing prevents other rules to trigger.

@hannibal85, can you post your original code that caused you to see this behavior? Did it also involve a System started rule?

The "problem" might be that changes to Items while ESH is starting up get suppressed (on purpose to avoid triggering rules with restoreOnStartup?) which is a different problem from Thread::sleep blocking all rules from firing.

Another alternative is can you change your code above to use a manual trigger rather than System started?

**Comment by georgeerhan** [comment]
> The "problem" might be that changes to Items while ESH is starting up get suppressed (on purpose to avoid triggering rules with restoreOnStartup?) which is a different problem from Thread::sleep blocking all rules from firing.
Indeed, I am testing this as we speak!

**Comment by hannibal85** [comment]
@rkoshak 

>  Did it also involve a System started rule?

Yes, the original code also included a System started trigger

> Another alternative is can you change your code above to use a manual trigger rather than System started?

Just tried this. And your are right. If I don't use the System started trigger but a manual trigger it works.

I myself already got more and more the feeling that this has nothing to do with Thread::sleep. I tried it with a rule trigger by System started but w/o Thread::sleep. The behaviour is more or less the same that other rules that should be called by the startup rule don't get triggered.

**Comment by georgeerhan** [comment]
So, after testing on build #1023, I can state the following:
If you fire two rules with system started trigger both having a thread.sleep instruction, one will be interrupted - that means that only one thread can be paused with a system started trigger (which seems reasonable in terms of code, but not in use cases!)
For the threads pausing when a rule is triggered with a thread sleep high enough (I tried 2 to 10 minutes) I can state that no other rule was affected on my setup!
These are the facts for now!

**Comment by kaikreuzer** [comment]
Thanks @hannibal85 and @georgeerhan for your thorough examinations - I think I was able to fix all the reported issues with #4185. It all looks pretty good in my tests and I hope you can confirm the same!

**Comment by hannibal85** [comment]
Thanks a lot for your work @kaikreuzer !
And also to all the other developers out there!

Of course I will try to confirm it with my example and give feedback here.
Starting with which snapshot of OH2 will this fix be included? I'm not really familiar with the procedure when ESH fixed or included in new OH builds

**Comment by kaikreuzer** [comment]
Issue is fixed in latest openHAB distro 1034.

**Comment by hannibal85** [comment]
Ok,
finally had the time to test latest OH2 build 1035 and my example from above just works fine after the upgrade.
Great!

**Comment by shorty707** [comment]
@kaikreuzer I am in build 1054 ... the issue still is there... thread::sleep pauses the whole rule engine.

**Comment by kaikreuzer** [comment]
Well, it definitely blocks a thread. And there is a limited number. As mentioned above, using Thread::sleep must not be done for any longer periods of time (more than a few seconds maybe).
The issue that was fixed was also specifically about startup rules.

**Comment by sheppy99** [comment]
Thread::sleep still seems to block the whole rule engine and this varies depending on the JVM used. I've just done extensive testing on my system running Snapshot build 1203 which had many Thread::sleep statements which have worked largely OK until recently when I changed from a Pi3 to a Debian PC and added a few more rules to work around the lack of GPIO Pins.
I documented it in a forum thread at https://community.openhab.org/t/oh2-2-crashing-randomly/37851/40?u=kevin
Is there any place where the thread numbers can be manually increased for those running larger systems on powerful hardware? I am running on Debian 64Bit with 8GB RAM and when fully loaded Java is using 10.6% of RAM and around usually less than 10% of one CPU core
