### ISSUE TITLE
Sonos:Notification:Amazon Echo Say Command is not played when player has been started by Amazon Echo

### ISSUE THREAD

**Issue by JueBag** [eclipse/smarthome#6752]
When player has been started before to play a radio station ordered via an Amazon Echo Dot (Sonos Skill) the say command is not performed.
After starting the radio station from the Sonos App it is working again.

**Comment by lolodomo** [comment]
Can you please check the value of the channels currenttransporturi and currenttrackuri after starting the radio from the EchoDot ?

**Comment by JueBag** [comment]
Starting from SonosApp:
currenttransporturi:
x-sonosapi-stream:s56851?sid=254&flags=8224&sn=0
currenttrackuri:
x-rincon-mp3radio://http://dg-ndr-http-dus-dtag-cdn.cast.addradio.de/ndr/ndr2/niedersachsen/mp3/128/stream.mp3?ar-distributor=f0a1

Starting from echoDot:
currenttransporturi:
x-rincon-mp3radio://http://opml.radiotime.com/Tune.ashx?id=e4747485&sid=s17492&formats=aac,mp3,hls&partnerId=rjyYMwEH&serial=AGBJNCPX3PKYUZHO6X43DV6MNPNQ
currenttrackuri:
x-rincon-mp3radio://http://dg-ndr-http-dus-dtag-cdn.cast.addradio.de/ndr/ndr2/niedersachsen/mp3/128/stream.mp3

**Comment by lolodomo** [comment]
Ok, that explains why the notification is not working.

Just to be sure, could you please confirm that the radio station you requested to EchoDot was `NDR 2` (station id `17492`) ?

Could you please try checking `currenttransporturi` value while asking EchoDot to play something else than a radio (Spotify, your music library, ...) ?

**Comment by JueBag** [comment]
Yes, it was NDR2! Although not sure about the StationID.

Playing something on Amazon Music (Own Music from NAS not possible with this Skill).

`x-rincon-queue:RINCON_949F3E7D2EF401400#6 `

**Comment by lolodomo** [comment]
No problem I found the station ID in your value and I just wanted to verify with you that it was really the station id. Now done.

I will try to handle your case, I think I know how to do it even if I am not yet sure if I should restore the radio station (after TTS) using the usual way or the EchoDot way.

**Comment by lolodomo** [comment]
Fix is merged.
Please close this issue.

**Comment by Andy2003** [comment]
This bug still does not seem to be fixed. I can reproduce it with OpenHAB 2.5.2. Once a radio station is started via Alexa, the `say` command will not work anymore.
